In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[667, 1787, 9062, 1875],
 [667, 1787, 9062, 8684],
 [667, 510, 9062, 3852],
 [5653, 5933, 3819, 5437, 481],
 [5653, 5933, 3819, 5437, 6438],
 [3031, 667, 7569, 9062, 4398],
 [2802, 5994, 6086, 5437]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  667 1787 9062 1875]
 [   0    0    0    0  667 1787 9062 8684]
 [   0    0    0    0  667  510 9062 3852]
 [   0    0    0 5653 5933 3819 5437  481]
 [   0    0    0 5653 5933 3819 5437 6438]
 [   0    0    0 3031  667 7569 9062 4398]
 [   0    0    0    0 2802 5994 6086 5437]]


In [9]:
## feature representation - dimensions
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 628ms/step


array([[[ 7.5473674e-03, -4.4685375e-02, -4.1036867e-02,  8.2088336e-03,
          2.0495344e-02, -6.8274848e-03, -4.4680059e-02, -4.6952963e-02,
          1.7097857e-02,  3.2624487e-02],
        [ 7.5473674e-03, -4.4685375e-02, -4.1036867e-02,  8.2088336e-03,
          2.0495344e-02, -6.8274848e-03, -4.4680059e-02, -4.6952963e-02,
          1.7097857e-02,  3.2624487e-02],
        [ 7.5473674e-03, -4.4685375e-02, -4.1036867e-02,  8.2088336e-03,
          2.0495344e-02, -6.8274848e-03, -4.4680059e-02, -4.6952963e-02,
          1.7097857e-02,  3.2624487e-02],
        [ 7.5473674e-03, -4.4685375e-02, -4.1036867e-02,  8.2088336e-03,
          2.0495344e-02, -6.8274848e-03, -4.4680059e-02, -4.6952963e-02,
          1.7097857e-02,  3.2624487e-02],
        [-5.1920526e-03, -2.5300145e-02,  2.6265454e-02, -2.2981418e-02,
          2.2246614e-03, -1.0085478e-03, -4.5245565e-02, -1.0574959e-02,
          1.3200138e-02,  9.1581717e-03],
        [ 1.8952791e-02,  6.6658370e-03, -2.6128400e-02,  1.